<a href="https://colab.research.google.com/github/marioarsw/AnaliticaDescriptiva/blob/main/practicas/practica17_267370.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Maestría en Inteligencia Artificial y Analítica de Datos


*   Curso: Programación para Analítica Descriptiva y Predictiva
*   Semestre: Enero-Junio
*   Profesor: Dr. Vicente García Jiménez

## Mario Amador - 267370.

El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos categóricos.

Instrucciones:

1. Descarga el archivo CSV, nls97, proporcionado en esta tarea. También lo puedes encontrar en recursos.
2. Crea un notebook en colab y guarda el archivo csv descargado en tu drive.
3. Agrega secciones en el colab poniendo como título el nombre de cada ejercicio.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/Unidad02/nls97.csv')
df.head(5)

,personid,gender,birthmonth,birthyear,highestgradecompleted,maritalstatus,childathome,childnotathome,wageincome,weeklyhrscomputer,...,colenrfeb13,colenroct13,colenrfeb14,colenroct14,colenrfeb15,colenroct15,colenrfeb16,colenroct16,colenrfeb17,colenroct17
0,100061,Female,5,1980,13.0,Married,4.0,0.0,12500.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
1,100139,Male,9,1983,12.0,Married,2.0,0.0,120000.0,1 to 3 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
2,100284,Male,11,1984,7.0,Never-married,1.0,0.0,58000.0,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
3,100292,Male,4,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,NaN,NaN,NaN,NaN
4,100583,Male,1,1980,13.0,Married,4.0,0.0,30000.0,Less than 1 hour a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled

# Ejercicio 01: Errores Tipográficos y Valores Inconsistentes: maritalstatus

1. Imprime de la columna 'maritalstatus' los valores únicos.
2. Imprime la frecuencia de cada valor único
3. Cambia el valor 'Never-Married' a 'Single'
4. Imprime la frecuencia de cada valor único.

1. Imprime de la columna 'maritalstatus' los valores únicos.

In [6]:
df['maritalstatus'].unique()

array(['Married', 'Never-married', nan, 'Divorced', 'Separated',
       'Widowed'], dtype=object)

2. Imprime la frecuencia de cada valor único

In [7]:
df['maritalstatus'].value_counts()

maritalstatus
Married          3066
Never-married    2766
Divorced          663
Separated         154
Widowed            23
Name: count, dtype: int64

3. Cambia el valor 'Never-Married' a 'Single'

In [15]:
df['maritalstatus'] = df['maritalstatus'].str.strip()

In [18]:
df['maritalstatus'] = df['maritalstatus'].replace('Never-married', 'Single')

4. Imprime la frecuencia de cada valor único.

In [19]:
df['maritalstatus'].value_counts()

maritalstatus
Married      3066
Single       2766
Divorced      663
Separated     154
Widowed        23
Name: count, dtype: int64

# Ejercicio 02: Errores Tipográficos y Valores Inconsistentes: highestdegree.

1. Imprime de la columna 'highestdegrees' los valores únicos.
2. Imprime la frecuencia de cada valor único
3. Observa que cada valor categórico empieza con 0. Modifica las categorías para que todas estén en minúsculas y ninguna empiece con un número. Por ejemplo, si dice "2. High School", debería ser 'high school.
4. Los cambios se realizarán en la misma columna 'highestdegrees'.
5. Imprime los nuevos valores únicos.

1. Imprime de la columna 'highestdegrees' los valores únicos.

In [20]:
df['highestdegree'].unique()

array(['2. High School', '0. None', '4. Bachelors', '3. Associates',
       '5. Masters', '1. GED', '7. Professional', '6. PhD', nan],
      dtype=object)

2. Imprime la frecuencia de cada valor único.

In [21]:
df['highestdegree'].value_counts()

highestdegree
2. High School     3667
4. Bachelors       1673
1. GED             1146
0. None             953
3. Associates       737
5. Masters          603
7. Professional     120
6. PhD               54
Name: count, dtype: int64

3. Observa que cada valor categórico empieza con 0. Modifica las categorías para que todas estén en minúsculas y ninguna empiece con un número. Por ejemplo, si dice "2. High School", debería ser 'high school.

In [22]:
df['highestdegree'] = df['highestdegree'].str.strip().str.lower().str.replace(r'^\d\.\s*', '', regex=True)
# ^ inicio
# \d+ 1 o más dígitos
# \. punto lit
# \s* 0 o más espacios

In [23]:
df['highestdegree'].unique()

array(['high school', 'none', 'bachelors', 'associates', 'masters', 'ged',
       'professional', 'phd', nan], dtype=object)

In [24]:
# frecuencias, aunque deberían ser las mismas
df['highestdegree'].value_counts()

highestdegree
high school     3667
bachelors       1673
ged             1146
none             953
associates       737
masters          603
professional     120
phd               54
Name: count, dtype: int64

# Ejercicio 03: Alta Cardinalidad - Frecuencias Bajas

1. De la columna 'maritalstatus' une las categorías Widowed y 'Single' en una categoría más general llamada 'Single/No Partner'. Crea una nueva columna, 'marital_grouped' donde aparezcan las nuevas categorías de maritalstatus.
2. Imprime los valores únicos de la nueva columna 'marital_grouped'.
3. Imprime la frecuencia de los valores únicos de la nueva columna 'marital_grouped'.

1. De la columna 'maritalstatus' une las categorías Widowed y 'Single' en una categoría más general llamada 'Single/No Partner'. Crea una nueva columna, 'marital_grouped' donde aparezcan las nuevas categorías de maritalstatus.

In [25]:
df['marital_grouped'] = df['maritalstatus'].replace(['Widowed', 'Single'], 'Single/No Partner')
df

,personid,gender,birthmonth,birthyear,highestgradecompleted,maritalstatus,childathome,childnotathome,wageincome,weeklyhrscomputer,...,colenroct13,colenrfeb14,colenroct14,colenrfeb15,colenroct15,colenrfeb16,colenroct16,colenrfeb17,colenroct17,marital_grouped
0,100061,Female,5,1980,13.0,Married,4.0,0.0,12500.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Married
1,100139,Male,9,1983,12.0,Married,2.0,0.0,120000.0,1 to 3 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Married
2,100284,Male,11,1984,7.0,Single,1.0,0.0,58000.0,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Single/No Partner
3,100292,Male,4,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,NaN,NaN,NaN,NaN,NaN
4,100583,Male,1,1980,13.0,Married,4.0,0.0,30000.0,Less than 1 hour a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Married
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8979,999291,Female,4,1981,16.0,Married,NaN,NaN,35000.0,7 to 9 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Married
8980,999406,Male,7,1982,14.0,Single,NaN,NaN,116000.0,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Single/No Partner
8981,999543,Female,8,1984,12.0,Divorced,2.0,0.0,NaN,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Divorced
8982,999698,Female,5,1983,12.0,Single,5.0,0.0,NaN,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Single/No Partner
8983,999963,Female,9,1982,17.0,Married,2.0,0.0,50000.0,4 to 6 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,Married

2. Imprime los valores únicos de la nueva columna 'marital_grouped'.

In [26]:
df['marital_grouped'].unique()

array(['Married', 'Single/No Partner', nan, 'Divorced', 'Separated'],
      dtype=object)

3. Imprime la frecuencia de los valores únicos de la nueva columna 'marital_grouped'.

In [27]:
df['marital_grouped'].value_counts()

marital_grouped
Married              3066
Single/No Partner    2789
Divorced              663
Separated             154
Name: count, dtype: int64

# Ejercicio 04: Tipos de Datos

1. Imprime el tipo de datos de la columna gender.
2. Imprime la cantidad de bytes de dicha columna.
3. Si la columna es de tipo object, modifica a category.
4. En caso de haber realizado la modificación del tipo de datos, imprime la cantidad de bytes que ocupa dicha columna con el nuevo tipo de datos.

1. Imprime el tipo de datos de la columna gender.

In [28]:
df['gender'].dtype

dtype('O')

2. Imprime la cantidad de bytes de dicha columna.

In [30]:
df['gender'].memory_usage(deep=True)

485054

3. Si la columna es de tipo object, modifica a category.

In [31]:
df['gender'] = df['gender'].astype('category')

4. En caso de haber realizado la modificación del tipo de datos, imprime la cantidad de bytes que ocupa dicha columna con el nuevo tipo de datos.

In [32]:
df['gender'].dtype

CategoricalDtype(categories=['Female', 'Male'], ordered=False, categories_dtype=object)

In [33]:
df['gender'].memory_usage(deep=True)

9332